# Configuration file for custom scenarios for `premise`
---
regionalize:
  datasets:
    - name: ammonia production, hydrogen from electrolysis
      reference product: ammonia, anhydrous, liquid
      exists in original database: True
    - name: ammonia production, steam reforming
      reference product: ammonia, anhydrous, liquid
      exists in original database: True
    - name: methanol production, from natural gas reforming
      reference product: methanol
      exists in original database: True

production pathways:
  # Ammonia H2
  ammonia_h2:
    production volume:
      variable: Ammonia|Ammonia H2
    ecoinvent alias:
      name: ammonia production, hydrogen from electrolysis
      reference product: ammonia, anhydrous, liquid
      exists in original database: True

  # Ammonia SMR
  ammonia_smr:
    production volume:
      variable: Ammonia|Ammonia SMR
    ecoinvent alias:
      name: ammonia production, steam reforming
      reference product: ammonia, anhydrous, liquid
      exists in original database: True

  methanol_h2:
    production volume:
      variable: Methanol|Methanol H2
    ecoinvent alias:
      name: methanol distillation, hydrogen from electrolysis, CO2 from DAC #Bold assumption, to be refined
      reference product: methanol, purified
      exists in original database: True

  # Ammonia SMR
  methanol_smr:
    production volume:
      variable: Methanol|Methanol SMR
    ecoinvent alias:
      name: methanol production, from natural gas reforming
      reference product: methanol
      exists in original database: True

  # Ethylene pathways

markets:
  - name: market for ammonia (SPS)
    reference product: ammonia, anhydrous, liquid
    unit: kilogram
    includes:
      - ammonia_h2
      - ammonia_smr

    #from original activity:
    add:
      - name: market for transport, freight, train, fleet average
        reference product: transport, freight, train, fleet average
        amount: 0.0438196700916739

      - name: market for transport, freight, inland waterways, barge, diesel
        reference product: transport, freight, inland waterways, barge, diesel
        amount: 0.0438196700916739

      - name: market for transport, freight, lorry, unspecified
        reference product: transport, freight, lorry, diesel, unspecified
        amount: 0.171298965541689

    replaces:
      - name: market for ammonia, anhydrous, liquid
        product: ammonia, anhydrous, liquid
        operator: equals

      - name: ammonia production, steam reforming, liquid
        product: ammonia, anhydrous, liquid
        operator: equals

      - name: ammonia production, steam reforming
        product: ammonia, anhydrous, liquid
        operator: equals

      - name: ammonia production, steam reforming with syngas CCS
        product: ammonia, anhydrous, liquid
        operator: equals

      - name: ammonia production, steam reforming with syngas and flue gas CCS
        product: ammonia, anhydrous, liquid
        operator: equals

      - name: ammonia production, hydrogen from coal gasification with CCS
        product: ammonia, anhydrous, liquid
        operator: equals

      - name: ammonia production, hydrogen from electrolysis
        product: ammonia, anhydrous, liquid
        operator: equals

      - name: ammonia production, partial oxidation, liquid
        product: ammonia, anhydrous, liquid
        operator: equals

      - name: ammonia production, hydrogen from methane pyrolysis
        product: ammonia, anhydrous, liquid
        operator: equals

      - name: ammonia production, hydrogen from coal gasification
        product: ammonia, anhydrous, liquid
        operator: equals
  
  - name: market for methanol (SPS)
    reference product: methanol
    unit: kilogram
    includes:
      - methanol_h2
      - methanol_smr

    #from original activity:
    add:
      - name: market for transport, freight, train, fleet average
        reference product: transport, freight, train, fleet average
        amount: 0.04381967

      - name: market for transport, freight, inland waterways, barge, diesel
        reference product: transport, freight, inland waterways, barge, diesel
        amount: 0.021869035

      - name: market for transport, freight, lorry, unspecified
        reference product: transport, freight, lorry, diesel, unspecified
        amount: 0.171298966

    replaces:
      - name: market for methanol
        product: methanol
        #operator: equals

      - name: methanol production, from coal gasification
        product: methanol
        #operator: equals

      #- name: methanol production, from natural gas reforming
      #  product: methanol
      #  operator: equals

      #- name: methanol production, biomass gasification
      #  product: methanol
      #  operator: equals